name       : intel-undervolt
version    : '1.6'
release    : 2
source     :
    - https://github.com/kitsunyan/intel-undervolt/archive/1.6.tar.gz : 8ec57c14a9f95eb29e3f6349b935c577fa1b8567e1c3c5337f9d11d05448815d
license    : GPL-3.0-or-later
component  : system.utils
summary    : Intel CPU undervolting tool
description: |
    intel-undervolt is a tool for undervolting Haswell and newer Intel CPUs
    using MSR. DISCLAIMER - Solus and/or The Solus team take no responsibility
    for any damage caused to your hardware from the incorrect use of the
    intel-undervolt software.
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-Solus-liability-waiver.patch
build      : |
    %make
install    : |
    %make_install
