name       : intel-undervolt
version    : 1.5
release    : 1
source     :
    - https://github.com/kitsunyan/intel-undervolt/archive/1.5.tar.gz : cf30fb2651eee8bb15e89be7964157ebe0aeeb1bb518ec1706cd508b147348f4
license    : GPL-3.0-or-later
component  : system.utils
summary    : Intel CPU undervolting tool
description: |
    intel-undervolt is a tool for undervolting Haswell and newer Intel CPUs
    using MSR. DISCLAIMER - Solus and/or The Solus team take no responsibility
    for any damage caused to your hardware from the incorrect use of the
    intel-undervolt software.
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-Solus-liability-waiver.patch
build      : |
    %make
install    : |
    %make_install
